spring:

  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TecHelp;encrypt=true;trustServerCertificate=true
<<<<<<< HEAD
    username: api_user
    password: Xande8160
=======
    username: sa
    password: 30112004As
>>>>>>> 89ac0d2685a46c2149fe250889388cfc52e677ab
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  jackson:
    time-zone: America/Sao_Paulo
    date-format: dd/MM/yyyy


server:
  port: 8080
  servlet:
    context-path: /techelp/api

logging:
  level:
    br.com.TecHelpAPI: INFO
    root: WARN


